# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Two-machine Vagrant setup for Tailscale CNI development:
#   - control-plane: Kubernetes API server / control plane
#   - node: Worker node for CNI testing
#

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "control-plane" do |cp|
    cp.vm.hostname = "ts-cni-dev-control-plane"
    cp.vm.network "private_network", ip: "192.168.56.10"
    cp.vm.network "forwarded_port", guest: 6443, host: 16443, host_ip: "127.0.0.1"
    cp.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
      # vb.gui = true
    end
  end

  config.vm.define "node" do |node|
    node.vm.hostname = "ts-cni-dev-node"
    node.vm.network "private_network", ip: "192.168.56.11"
    node.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
  end

  # Works around some weird config issues - tailscale dns breaks, and also
  # sometimes the hostnames get messed up. We disable the service, start it
  # after vagrant does its thing, and set the default DNS manually.
  $network_script = <<-SCRIPT
if [ -f  /usr/bin/tailscale ]; then systemctl start tailscaled; fi
resolvectl dns eth0 10.0.2.3
SCRIPT

  config.vm.provision :shell, inline: $network_script, run: 'always'

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.limit = "all"
  end
end
